In [25]:
using Plots; gr()
using Interact

## Functions

A **function** is the most fundamental concept in computing (and also in mathematics). 
A function is a piece of a program that receives **input arguments**, processes them by doing certain calculations on them, and returns **outputs**.

Julia allows us to define simple functions in a simple way. For example, a sigmoid function that we will use extensively later in the course can be defined by the equation

$$\sigma(x) := \frac{1}{1 + \exp(-x)}.$$

Julia allows us to define this function with the following simple syntax:

In [26]:
σ(x) = 1 / (1 + exp(-x))

σ (generic function with 1 method)

We can plot this function to see what it looks like:

In [27]:
plot(σ, -5, 5)
hline!([0, 1], ls=:dash, lw=3)
vline!([0], ls=:dash, lw=3)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -4 
 
 
 -2 
 
 
 0 
 
 
 2 
 
 
 4 
 
 
 0.0 
 
 
 0.2 
 
 
 0.4 
 
 
 0.6 
 
 
 0.8 
 
 
 1.0 
 
<polyline clip-path="url(#clip9102)" style="stroke:#009af9; stroke-width:1; stroke-opacity:1; fill:none" points="
 32.4745,373.184 83.0814,369.316 113.494,364.739 139.208,358.568 153.174,353.967 167.14,348.239 180.015,341.771 192.89,333.978 206.694,323.947 220.498,311.99 
 236.491,295.548 252.484,276.278 266.697,256.923 280.91,235.799 293.373,216.212 305.837,196.086 333.013,152.675 360.352,113.484 375.465,94.9397 390.577,78.9126 
 404.957,65.9869 419.337,55.1873 434.288,45.9837 449.24,38.57 461.826,33.5084 474.412,29.3544 505.144,22.1598 534.033,18.0631 580.315,14.5753 
 "/>
 
 
 
 
 
 
 
 y1 
 
 
 
 y2 
 
 
 
 y3

This particular function takes any real number as input, and gives an output between $0$ and $1$. It is continuous and smooth.

## Parameters

Instead of a single function, we can think about a whole class (set) of functions that look similar but differ in the value of a **parameter**.  Let's make a new function that uses the previous $\sigma$ function, but also has a parameter, $w$. Note that Julia treats parameters just as extra arguments:

$$f_w(x) = f(x; w) = \sigma(w \, x).$$

Mathematically speaking, we can think of $f_w$ as a different function for each different value of the parameter $w$.

In Julia, this becomes

In [28]:
f(x, w) = σ(w * x)

f (generic function with 1 method)

Note that Julia just treats parameters as additional arguments to the function.

Mathematically we can write this in two different ways:

$$f(x; w) = f_w(x).$$

We can now investigate the effect of $w$ interactively. To do so, we need a way of writing in Julia "the function of one variable $x$ that we obtain when we fix the value of $w". We write this as an "anonymous function":

    x -> f(x, w)
    
We can read this as "the function that maps $x$ to the value of $f(x, w)$. 

In [29]:
@manipulate for w in -2:0.01:2
    plot(x->f(x, w), -5, 5, ylims=(0, 1))
end

Interact.Options{:SelectionSlider,Any}(33: "input-10" = 0.0 Any , "w", 0.0, "0.0", 201, Interact.OptionDict(DataStructures.OrderedDict{Any,Any}("-2.0"=>-2.0,"-1.99"=>-1.99,"-1.98"=>-1.98,"-1.97"=>-1.97,"-1.96"=>-1.96,"-1.95"=>-1.95,"-1.94"=>-1.94,"-1.93"=>-1.93,"-1.92"=>-1.92,"-1.91"=>-1.91…), Dict{Any,Any}(Pair{Any,Any}(-0.92, "-0.92"),Pair{Any,Any}(1.2, "1.2"),Pair{Any,Any}(1.68, "1.68"),Pair{Any,Any}(-0.22, "-0.22"),Pair{Any,Any}(-1.78, "-1.78"),Pair{Any,Any}(1.19, "1.19"),Pair{Any,Any}(-1.23, "-1.23"),Pair{Any,Any}(0.22, "0.22"),Pair{Any,Any}(-1.16, "-1.16"),Pair{Any,Any}(0.2, "0.2")…)), Any[], Any[], true, "horizontal")

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -4 
 
 
 -2 
 
 
 0 
 
 
 2 
 
 
 4 
 
 
 0.0 
 
 
 0.2 
 
 
 0.4 
 
 
 0.6 
 
 
 0.8 
 
 
 1.0 
 
 
 
 
 
 
 y1

## Fitting a function to data

Suppose we are given a single data point $(x_1, y_1) = (2, 0.8)$. We can try to "fit" a function $f_w$ by adjusting the parameter $w$ until the function passes through the data:

In [30]:
@manipulate for w in -2:0.01:2
    plot(x->f(x, w), -5, 5, ylims=(0, 1))
    scatter!([2], [0.8])
end

Interact.Options{:SelectionSlider,Any}(37: "input-11" = 0.0 Any , "w", 0.0, "0.0", 201, Interact.OptionDict(DataStructures.OrderedDict{Any,Any}("-2.0"=>-2.0,"-1.99"=>-1.99,"-1.98"=>-1.98,"-1.97"=>-1.97,"-1.96"=>-1.96,"-1.95"=>-1.95,"-1.94"=>-1.94,"-1.93"=>-1.93,"-1.92"=>-1.92,"-1.91"=>-1.91…), Dict{Any,Any}(Pair{Any,Any}(-0.92, "-0.92"),Pair{Any,Any}(1.2, "1.2"),Pair{Any,Any}(1.68, "1.68"),Pair{Any,Any}(-0.22, "-0.22"),Pair{Any,Any}(-1.78, "-1.78"),Pair{Any,Any}(1.19, "1.19"),Pair{Any,Any}(-1.23, "-1.23"),Pair{Any,Any}(0.22, "0.22"),Pair{Any,Any}(-1.16, "-1.16"),Pair{Any,Any}(0.2, "0.2")…)), Any[], Any[], true, "horizontal")

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -4 
 
 
 -2 
 
 
 0 
 
 
 2 
 
 
 4 
 
 
 0.0 
 
 
 0.2 
 
 
 0.4 
 
 
 0.6 
 
 
 0.8 
 
 
 1.0 
 
 
 
 
 
 
 
 
 y1 
 
 
 
 
 y2

We can calculate how we are from the goal, for example by finding the vertical distance from the curve to the point.
We will call this function $C$; it is a function of $w$:

$$C(w) = (y_1 - f(x_1, w))^2.$$

In [31]:
@manipulate for w in -2:0.01:2
    plot(x->f(x, w), -5, 5, ylims=(0, 1))

    x1, y1 = 2, 0.8
    
    plot!([x1, x1], [y1, f(x1, w)])
    scatter!([x1], [y1])
    title!("Distance^2 = $((y1 - f(x1, w))^2)")

end

Interact.Options{:SelectionSlider,Any}(41: "input-12" = 0.0 Any , "w", 0.0, "0.0", 201, Interact.OptionDict(DataStructures.OrderedDict{Any,Any}("-2.0"=>-2.0,"-1.99"=>-1.99,"-1.98"=>-1.98,"-1.97"=>-1.97,"-1.96"=>-1.96,"-1.95"=>-1.95,"-1.94"=>-1.94,"-1.93"=>-1.93,"-1.92"=>-1.92,"-1.91"=>-1.91…), Dict{Any,Any}(Pair{Any,Any}(-0.92, "-0.92"),Pair{Any,Any}(1.2, "1.2"),Pair{Any,Any}(1.68, "1.68"),Pair{Any,Any}(-0.22, "-0.22"),Pair{Any,Any}(-1.78, "-1.78"),Pair{Any,Any}(1.19, "1.19"),Pair{Any,Any}(-1.23, "-1.23"),Pair{Any,Any}(0.22, "0.22"),Pair{Any,Any}(-1.16, "-1.16"),Pair{Any,Any}(0.2, "0.2")…)), Any[], Any[], true, "horizontal")

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -4 
 
 
 -2 
 
 
 0 
 
 
 2 
 
 
 4 
 
 
 0.0 
 
 
 0.2 
 
 
 0.4 
 
 
 0.6 
 
 
 0.8 
 
 
 1.0 
 
 
 Distance^2 = 0.09000000000000002 
 
 
 
 
 
 
 
 
 
 y1 
 
 
 
 y2 
 
 
 
 
 y3

Let's draw $C(w)$ as a function of the parameter $w$:

In [32]:
x0, y0 = 2.0, 0.8

plot(w->(y0 - f(x0, w))^2, -3, 3, xlabel="w", ylabel="C(w)", ylims=(0, 0.7))

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -2 
 
 
 -1 
 
 
 0 
 
 
 1 
 
 
 2 
 
 
 0.0 
 
 
 0.1 
 
 
 0.2 
 
 
 0.3 
 
 
 0.4 
 
 
 0.5 
 
 
 0.6 
 
 
 w 
 
 
 C(w) 
 
<polyline clip-path="url(#clip9902)" style="stroke:#009af9; stroke-width:1; stroke-opacity:1; fill:none" points="
 48.2225,43.8749 97.3747,48.1365 126.913,53.9257 151.887,62.5398 165.452,69.3974 179.017,78.3255 191.522,88.8126 204.027,101.875 217.434,119.154 230.841,140.121 
 246.375,169.024 261.908,202.119 275.712,233.596 289.516,265 301.622,290.676 313.727,313.101 320.325,323.56 326.924,332.634 333.523,340.282 340.122,346.519 
 346.76,351.436 353.398,355.096 360.036,357.637 366.675,359.211 381.353,360.052 396.032,358.544 409.998,356.073 423.964,353.324 453.007,348.26 477.456,345.249 
 507.304,342.949 535.363,341.724 580.315,340.786 
 "/>
 
 
 
 
 y1

We see that there is a special value of $w$ where the function $C$ reaches $0$, since for this value of $w$, the graph of $f$ does pass exactly through the point $(x_0, y_0)$. We could find the place $w^*$ where the function hits $0$ by zooming in on that piece of the graph.

In [33]:
x0, y0 = 2.0, 0.8
@manipulate for w in -2:0.1:2
    plot(w->(y0 - f(x0, w))^2, -3, 3, xlabel="w", ylabel="C(w)", ylims=(0, 0.7))
    vline!([w])
    title!("Vertical line at w = $w")
end

Interact.Options{:SelectionSlider,Any}(45: "input-13" = 0.0 Any , "w", 0.0, "0.0", 21, Interact.OptionDict(DataStructures.OrderedDict{Any,Any}("-2.0"=>-2.0,"-1.9"=>-1.9,"-1.8"=>-1.8,"-1.7"=>-1.7,"-1.6"=>-1.6,"-1.5"=>-1.5,"-1.4"=>-1.4,"-1.3"=>-1.3,"-1.2"=>-1.2,"-1.1"=>-1.1…), Dict{Any,Any}(Pair{Any,Any}(1.0, "1.0"),Pair{Any,Any}(0.3, "0.3"),Pair{Any,Any}(1.2, "1.2"),Pair{Any,Any}(2.0, "2.0"),Pair{Any,Any}(-0.2, "-0.2"),Pair{Any,Any}(-1.0, "-1.0"),Pair{Any,Any}(1.5, "1.5"),Pair{Any,Any}(-1.3, "-1.3"),Pair{Any,Any}(-0.3, "-0.3"),Pair{Any,Any}(-0.6, "-0.6")…)), Any[], Any[], true, "horizontal")

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -2 
 
 
 -1 
 
 
 0 
 
 
 1 
 
 
 2 
 
 
 0.0 
 
 
 0.1 
 
 
 0.2 
 
 
 0.3 
 
 
 0.4 
 
 
 0.5 
 
 
 0.6 
 
 
 Vertical line at w = 0.0 
 
 
 w 
 
 
 C(w) 
 
<polyline clip-path="url(#clip0102)" style="stroke:#009af9; stroke-width:1; stroke-opacity:1; fill:none" points="
 48.2225,61.7478 97.3747,65.7685 126.913,71.2305 151.887,79.3578 165.452,85.8279 179.017,94.2514 191.522,104.146 204.027,116.47 217.434,132.773 230.841,152.555 
 246.375,179.824 261.908,211.049 275.712,240.747 289.516,270.375 301.622,294.601 313.727,315.758 320.325,325.626 326.924,334.187 333.523,341.403 340.122,347.288 
 346.76,351.926 353.398,355.38 360.036,357.777 366.675,359.263 381.353,360.056 396.032,358.633 409.998,356.301 423.964,353.708 453.007,348.931 477.456,346.09 
 507.304,343.92 535.363,342.763 580.315,341.879 
 "/>
 
 
 
 
 
 y1 
 
 
 
 y2

Why did we use such a complicated function $C$ with those squares inside? We could just take the distance (instead of the distance squared) using the absolute value function:

In [34]:
x0, y0 = 2.0, 0.8

plot(w->abs(y0 - f(x0, w)), -3, 3, xlabel="w", ylabel="C_abs(w)", ylims=(0, 0.7))

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -2 
 
 
 -1 
 
 
 0 
 
 
 1 
 
 
 2 
 
 
 0.0 
 
 
 0.1 
 
 
 0.2 
 
 
 0.3 
 
 
 0.4 
 
 
 0.5 
 
 
 0.6 
 
 
 w 
 
 
 C_abs(w) 
 
<polyline clip-path="url(#clip0302)" style="stroke:#009af9; stroke-width:1; stroke-opacity:1; fill:none" points="
 48.2225,-36.5646 97.3747,-33.8828 126.913,-30.2101 151.887,-24.6804 165.452,-20.2207 179.017,-14.3351 191.522,-7.30126 204.027,1.65274 217.434,13.8531 230.841,29.2606 
 238.608,39.8495 246.375,51.759 254.141,65.0444 261.908,79.7297 275.712,109.209 289.516,142.564 301.622,174.232 313.727,207.162 326.924,243.171 340.122,277.854 
 346.76,294.382 353.398,310.119 360.036,324.965 366.675,338.849 370.344,346.093 374.014,353.027 375.849,356.376 377.683,359.647 379.518,357.402 381.353,354.287 
 388.692,342.598 396.032,332.109 409.998,315.24 423.964,301.965 438.486,291.334 453.007,283.299 465.232,278.126 477.456,274.099 507.304,267.685 535.363,264.444 
 580.315,262.036 
 "/>
 
 
 
 
 y1

Now we see why squares are generally preferred: using the absolute value gives a cost function that is *not smooth*. This makes it difficult to use methods from calculus to find the minimum. Nonetheless, using non-smooth functions is much more common nowadays.

## More data

Suppose there are now two data points to fit, the previous $(x_1, y_1)$ together with $(x_2, y_2) = (-3, 0.3)$.
We will calculate the cost function as the sum of the squared vertical distances from the graph to each data point:

In [35]:
xs = [2, -3]
ys = [0.8, 0.3]

@manipulate for w in -2:0.01:2
    plot(x->f(x, w), -5, 5, ylims=(0, 1))
    
    scatter!(xs, ys)

    for i in 1:2
        plot!([xs[i], xs[i]], [ys[i], f(xs[i], w)])
    end
    
    d² = sum(abs2, ys .- f.(xs, w))
    
    title!("Distance^2 = $(d²)")

end

Interact.Options{:SelectionSlider,Any}(49: "input-14" = 0.0 Any , "w", 0.0, "0.0", 201, Interact.OptionDict(DataStructures.OrderedDict{Any,Any}("-2.0"=>-2.0,"-1.99"=>-1.99,"-1.98"=>-1.98,"-1.97"=>-1.97,"-1.96"=>-1.96,"-1.95"=>-1.95,"-1.94"=>-1.94,"-1.93"=>-1.93,"-1.92"=>-1.92,"-1.91"=>-1.91…), Dict{Any,Any}(Pair{Any,Any}(-0.92, "-0.92"),Pair{Any,Any}(1.2, "1.2"),Pair{Any,Any}(1.68, "1.68"),Pair{Any,Any}(-0.22, "-0.22"),Pair{Any,Any}(-1.78, "-1.78"),Pair{Any,Any}(1.19, "1.19"),Pair{Any,Any}(-1.23, "-1.23"),Pair{Any,Any}(0.22, "0.22"),Pair{Any,Any}(-1.16, "-1.16"),Pair{Any,Any}(0.2, "0.2")…)), Any[], Any[], true, "horizontal")

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -4 
 
 
 -2 
 
 
 0 
 
 
 2 
 
 
 4 
 
 
 0.0 
 
 
 0.2 
 
 
 0.4 
 
 
 0.6 
 
 
 0.8 
 
 
 1.0 
 
 
 Distance^2 = 0.13000000000000003 
 
 
 
 
 
 
 
 
 
 
 
 
 y1 
 
 
 
 
 y2 
 
 
 
 y3 
 
 
 
 y4

In [36]:
?sum

search: sum sum! sumabs summary sumabs2 sum_kbn cumsum cumsum! consume



```
sum(f, itr)
```

Sum the results of calling function `f` on each element of `itr`.

```jldoctest
julia> sum(abs2, [2; 3; 4])
29
```

```
sum(itr)
```

Returns the sum of all elements in a collection.

```jldoctest
julia> sum(1:20)
210
```

```
sum(A, dims)
```

Sum elements of an array over the given dimensions.

```jldoctest
julia> A = [1 2; 3 4]
2×2 Array{Int64,2}:
 1  2
 3  4

julia> sum(A, 1)
1×2 Array{Int64,2}:
 4  6

julia> sum(A, 2)
2×1 Array{Int64,2}:
 3
 7
```


After playing with this for a while, it is intuitively obvious that we cannot make the function pass through both data points for any value of $w$. 
Now we have the following cost function:

$$C(w) = \sum_i [y_i - f_w(x_i)]^2$$

Let's plot it:

In [37]:
C(w) = sum(abs2, ys .- f.(xs, w))

plot(C, -1, 1, xlabel="w", ylabel="C(w)", ylims=(0, 1.2))

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -0.75 
 
 
 -0.50 
 
 
 -0.25 
 
 
 0.00 
 
 
 0.25 
 
 
 0.50 
 
 
 0.75 
 
 
 0.00 
 
 
 0.25 
 
 
 0.50 
 
 
 0.75 
 
 
 1.00 
 
 
 w 
 
 
 C(w) 
 
<polyline clip-path="url(#clip0702)" style="stroke:#009af9; stroke-width:1; stroke-opacity:1; fill:none" points="
 54.9131,104.651 103.447,133.766 132.614,155.354 157.275,175.979 184.063,200.532 208.759,224.588 235.236,250.934 265.912,280.464 279.542,292.677 293.173,304.057 
 305.126,313.219 317.079,321.522 330.111,329.519 343.142,336.367 356.252,342.089 369.361,346.667 383.855,350.473 398.349,353.077 412.139,354.57 425.93,355.245 
 454.608,354.624 478.749,352.663 508.222,349.334 535.928,345.857 580.315,340.475 
 "/>
 
 
 
 
 y1

We see that $C$ has a minimum close to $0$ for a special value of $w$; let's call it $w^*$. From the graph, we can see that it's around $w^* \simeq 0.4$. We could again zoom in on that region of the graph to estimate it more precisely.

Isn't there a better way of using the computer to find this value of $w^*$?

## More parameters

If we add more parameters to a function, we may be able to improve how it fits to data. For example, we could define a new function $g$ with another parameter, a shift or **bias**:

$$g(x; w, b) := \sigma(w \, x) + b$$

In [38]:
g(x, w, b) = σ(w*x) + b

g (generic function with 1 method)

Let's try to fit this to the data:

In [39]:
xs = [2, -3]
ys = [0.8, 0.3]

@manipulate for w in -2:0.01:2, b in -2:0.01:2
    plot(x->g(x, w, b), -5, 5, ylims=(0, 1))
    
    scatter!(xs, ys)

    for i in 1:2
        plot!([xs[i], xs[i]], [ys[i], g(xs[i], w, b)])
    end
    
    d² = sum(abs2, ys .- g.(xs, w, b))
    
    title!("Distance^2 = $(d²)")

end

Interact.Options{:SelectionSlider,Any}(53: "input-15" = 0.0 Any , "w", 0.0, "0.0", 201, Interact.OptionDict(DataStructures.OrderedDict{Any,Any}("-2.0"=>-2.0,"-1.99"=>-1.99,"-1.98"=>-1.98,"-1.97"=>-1.97,"-1.96"=>-1.96,"-1.95"=>-1.95,"-1.94"=>-1.94,"-1.93"=>-1.93,"-1.92"=>-1.92,"-1.91"=>-1.91…), Dict{Any,Any}(Pair{Any,Any}(-0.92, "-0.92"),Pair{Any,Any}(1.2, "1.2"),Pair{Any,Any}(1.68, "1.68"),Pair{Any,Any}(-0.22, "-0.22"),Pair{Any,Any}(-1.78, "-1.78"),Pair{Any,Any}(1.19, "1.19"),Pair{Any,Any}(-1.23, "-1.23"),Pair{Any,Any}(0.22, "0.22"),Pair{Any,Any}(-1.16, "-1.16"),Pair{Any,Any}(0.2, "0.2")…)), Any[], Any[], true, "horizontal")

Interact.Options{:SelectionSlider,Any}(55: "input-16" = 0.0 Any , "b", 0.0, "0.0", 201, Interact.OptionDict(DataStructures.OrderedDict{Any,Any}("-2.0"=>-2.0,"-1.99"=>-1.99,"-1.98"=>-1.98,"-1.97"=>-1.97,"-1.96"=>-1.96,"-1.95"=>-1.95,"-1.94"=>-1.94,"-1.93"=>-1.93,"-1.92"=>-1.92,"-1.91"=>-1.91…), Dict{Any,Any}(Pair{Any,Any}(-0.92, "-0.92"),Pair{Any,Any}(1.2, "1.2"),Pair{Any,Any}(1.68, "1.68"),Pair{Any,Any}(-0.22, "-0.22"),Pair{Any,Any}(-1.78, "-1.78"),Pair{Any,Any}(1.19, "1.19"),Pair{Any,Any}(-1.23, "-1.23"),Pair{Any,Any}(0.22, "0.22"),Pair{Any,Any}(-1.16, "-1.16"),Pair{Any,Any}(0.2, "0.2")…)), Any[], Any[], true, "horizontal")

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -4 
 
 
 -2 
 
 
 0 
 
 
 2 
 
 
 4 
 
 
 0.0 
 
 
 0.2 
 
 
 0.4 
 
 
 0.6 
 
 
 0.8 
 
 
 1.0 
 
 
 Distance^2 = 0.13000000000000003 
 
 
 
 
 
 
 
 
 
 
 
 
 y1 
 
 
 
 
 y2 
 
 
 
 y3 
 
 
 
 y4

You should be able to convince yourself that we can now make the curve pass through both points simultaneously. 
Let's look at the graph of $C_2$, the cost function with both parameters:

In [40]:
C2(w, b) = sum(abs2, ys .- g.(xs, w, b))

C2 (generic function with 1 method)

In [41]:
?surface

search: surface surface! Surface schurfact schurfact!



No documentation found.

`Plots.surface` is a `Function`.

```
# 1 method for generic function "surface":
surface(args...; kw...) in Plots at /Users/jane/.julia/v0.6/RecipesBase/src/RecipesBase.jl:381
```


In [42]:
methods(surface)

# 1 method for generic function "surface":
surface(args...; kw...) in Plots at /Users/jane/.julia/v0.6/RecipesBase/src/RecipesBase.jl:381

In [43]:
plotlyjs()

Plots.PlotlyJSBackend()

In [44]:
ws = -2:0.05:2
bs = -2:0.05:2

surface(ws, bs, C2, alpha=0.8, zlims=(0,3))

If we rotate the surface around, we can see that indeed there is a unique point $(w^*, b^*)$ where the function $C_2$ attains its minimum.

If we add more data, however, we will again not be able to fit all of the data; we will only be able to attain a "best fit"

In [45]:
xs = [2, -3, -1, 1]
ys = [0.8, 0.3, 0.4, 0.4]

4-element Array{Float64,1}:
 0.8
 0.3
 0.4
 0.4

In [46]:

@manipulate for w in -2:0.01:2, b in -2:0.01:2
    plot(x->g(x, w, b), -5, 5, ylims=(-0.2, 1))
    
    scatter!(xs, ys)

    for i in 1:length(xs)
        plot!([xs[i], xs[i]], [ys[i], g(xs[i], w, b)])
    end
    
    d² = sum(abs2, ys .- g.(xs, w, b))
    
    title!("Distance^2 = $(d²)")

end

Interact.Options{:SelectionSlider,Any}(59: "input-17" = 0.0 Any , "w", 0.0, "0.0", 201, Interact.OptionDict(DataStructures.OrderedDict{Any,Any}("-2.0"=>-2.0,"-1.99"=>-1.99,"-1.98"=>-1.98,"-1.97"=>-1.97,"-1.96"=>-1.96,"-1.95"=>-1.95,"-1.94"=>-1.94,"-1.93"=>-1.93,"-1.92"=>-1.92,"-1.91"=>-1.91…), Dict{Any,Any}(Pair{Any,Any}(-0.92, "-0.92"),Pair{Any,Any}(1.2, "1.2"),Pair{Any,Any}(1.68, "1.68"),Pair{Any,Any}(-0.22, "-0.22"),Pair{Any,Any}(-1.78, "-1.78"),Pair{Any,Any}(1.19, "1.19"),Pair{Any,Any}(-1.23, "-1.23"),Pair{Any,Any}(0.22, "0.22"),Pair{Any,Any}(-1.16, "-1.16"),Pair{Any,Any}(0.2, "0.2")…)), Any[], Any[], true, "horizontal")

Interact.Options{:SelectionSlider,Any}(61: "input-18" = 0.0 Any , "b", 0.0, "0.0", 201, Interact.OptionDict(DataStructures.OrderedDict{Any,Any}("-2.0"=>-2.0,"-1.99"=>-1.99,"-1.98"=>-1.98,"-1.97"=>-1.97,"-1.96"=>-1.96,"-1.95"=>-1.95,"-1.94"=>-1.94,"-1.93"=>-1.93,"-1.92"=>-1.92,"-1.91"=>-1.91…), Dict{Any,Any}(Pair{Any,Any}(-0.92, "-0.92"),Pair{Any,Any}(1.2, "1.2"),Pair{Any,Any}(1.68, "1.68"),Pair{Any,Any}(-0.22, "-0.22"),Pair{Any,Any}(-1.78, "-1.78"),Pair{Any,Any}(1.19, "1.19"),Pair{Any,Any}(-1.23, "-1.23"),Pair{Any,Any}(0.22, "0.22"),Pair{Any,Any}(-1.16, "-1.16"),Pair{Any,Any}(0.2, "0.2")…)), Any[], Any[], true, "horizontal")

In [47]:
C2(w, b) = sum(abs2, ys .- g.(xs, w, b))

C2 (generic function with 1 method)

In [48]:
ws = -2:0.05:2
bs = -2:0.05:2

surface(ws, bs, C2, alpha=0.8, zlims=(0,3))